import "./globals.css";
import Header from "@/components/header/Header";
import { CartProvider } from "@/context/cartContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
